name: wanikani4mobile
description: WaniKani for Mobile.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  flutter_app_badger: ^1.1.2
  flutter_cache_manager: ^1.1.3
  flutter_launcher_icons: ^0.7.4
  flutter_local_notifications: ^0.9.1
  http: ^0.12.0
  mask_text_input_formatter: ^1.0.5
  provider: ^4.0.0
  shared_preferences: ^0.5.6
  url_launcher: ^5.4.1
  validators: ^2.0.0
  webview_flutter: ^0.3.18

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - res/

  uses-material-design: true

flutter_icons:
  # Note #1: run the following command to update the application icon:
  #          flutter pub run flutter_launcher_icons:main
  # Note #2: for Android, temporarily enlarge res/logo.png to 256x256 pixels big and do what is
  #          described at https://youtu.be/hpQenyqxTmw?t=394 and scale the logo to 88%.
  android: true
  ios: true
  image_path: "res/logo.png"
