name: wanikani4mobile
description: WaniKani for Mobile.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  flutter_launcher_icons: ^0.7.4
  provider: ^4.0.0
  shared_preferences: ^0.5.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

flutter_icons:
  # Note: run the following command to update the application icon:
  #       flutter pub run flutter_launcher_icons:main
  android: true
  ios: true
  image_path_android: "res/logo_android.png"
  image_path_ios: "res/logo_ios.png"
